load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = ["sol.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/code_practise/leetcode/lib:ds"
    ],
)