load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "40",
    srcs = ["40.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "1",
    srcs = ["1.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "2",
    srcs = ["2.cc"],
    deps = [
        "//src/code_practise/leetcode/lib:ds",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "3",
    srcs = ["3.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "4",
    srcs = ["4.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
